### ISSUE TITLE
Remove cosmos/iavl from lazyledger-core to stop dependency graph cycle

### ISSUE THREAD

**Issue by evan-forbes** [lazyledger/lazyledger-core#128]
Currently, we're trying to replace tendermint for lazyledger-core in the lazyerleger-app [#4](https://github.com/lazyledger/lazyledger-app/issues/4) and in the lazyledger fork of the cosmos-sdk [#2](https://github.com/lazyledger/cosmos-sdk/issues/2). We run into the same error if we attempt to change the import by using either the go modules' replace directive, or by using a script to manually replace every import from `"github.com/tendermint/tendermint"` to `"github.com/lazyledger/lazyledger-core"`. 
error:
```
go: github.com/cosmos/cosmos-sdk/baseapp imports
        github.com/tendermint/tendermint/abci/types imports
        github.com/lazyledger/lazyledger-core/crypto/ed25519: github.com/lazyledger/lazyledger-core@v0.32.7: parsing go.mod:
        module declares its path as: github.com/tendermint/tendermint
                but was required as: github.com/lazyledger/lazyledger-core

```

After digging through the dependency trees of the libraries, I found that lazyledger-core and the cosmos sdk are both importing different versions of the [cosmos/iavl](https://github.com/cosmos/iavl), and those two versions of the iavl each import their own version of tendermint. So, connecting the cosmos-sdk to lazyledger-core brings us to a special level of dependency hell, go.mod dependency hell, which stops go modules from reconciling the different module declariation of tendermint and its fork, lazyledger-core. [better explained in this post](https://github.com/golang/go/wiki/Resolving-Problems-From-Modified-Module-Path). 

![Screenshot from 2021-01-08 19-25-40](https://user-images.githubusercontent.com/42654277/104080707-503ada80-51ef-11eb-832e-4079f1eed5e9.png)

I think we're going to have to simultaneously update our fork of the cosmos-sdk, lazyledger-core, and a new fork of cosmos/iavl to new non-existent versions in order to break the import cycle. as described [here](https://github.com/golang/go/wiki/Resolving-Problems-From-Modified-Module-Path#a-harder-problem-removing-trailing-history)

**Comment by evan-forbes** [comment]
I also found another import cycle that stops go modules from updating the modules of lazyledger-core with `go get -u ./...`, that's caused by the recent switch from `github.com/liamsi/merkletree` to `github.com/lazyledger/merkletree`. But the import cycle is simpler, and can be fixed by updating the nmt module imported in lazyledger-core using `go get -u github.com/lazyledger/nmt`. 
![Screenshot from 2021-01-08 18-43-29](https://user-images.githubusercontent.com/42654277/104081092-1c14e900-51f2-11eb-8202-75d496d78f83.png)

**Comment by marbar3778** [comment]
Within lazyledger-core we can remove Iavl. It is used for testing light client queries but we will not be supporting these form of proofs (I believe). I can open a PR later today.

**Comment by liamsi** [comment]
It makes sense to remove IAVL from ll-core. AFAR, it is only used in tests only. 

Linking related issues discussions here for context:
 - https://github.com/lazyledger/lazyledger-core/pull/112#discussion_r541786991
 - https://github.com/tendermint/tendermint/issues/5694
 - https://github.com/cosmos/iavl/issues/46
 - https://github.com/cosmos/iavl/pull/125#discussion_r255904047
