### ISSUE TITLE
Update to tendermint 0.34.2

### ISSUE THREAD

**Issue by liamsi** [lazyledger/lazyledger-core#138]
As we are building the lazyledger app using the latest version of the SDK (https://github.com/lazyledger/cosmos-sdk/pull/11), we should update ll-core to use the equivalent of [0.34.1](https://github.com/tendermint/tendermint/releases/tag/v0.34.1) of tendermint.

ref: https://github.com/lazyledger/cosmos-sdk/issues/2

**Comment by liamsi** [comment]
We've already updated merged in few commits from tendermint master which didn't even land in 0.34.2 (as they are breaking). While it seemed to make sense at that time to always take the latest from tendermint, now that @evan-forbes started building the ll-app (which uses a version of the cosmos-sdk), it makes our lives more difficult: the SDK (even "the latest and greatest" from master) did just catch up with 0.34.2 a few days ago. 

Note: in the future, we should move a bit slower with updating from tendermint upstream and always stick to released versions, ideally which will be part of the SDK soon too - unless of course, we want to do the upgrading of our sdk fork ahead of the official sdk team. That said, I don't think we currently have the man-power for that nor is it a priority. In case we really want a change from tendermint master, we can still cherry-pick it (and if it's breaking update the SDK fork accordingly too).

We might even want to revert some of the changes that already made it into ll-core/master if that simplifies building a first version of the app.

**Comment by liamsi** [comment]
We use 0.34.1 together with a few changes that are breaking and won't land in 0.34.2 but into the next "major" release (0.35.0). I think we can actually close this issue for now and cherry-pick any changes if we want them (either from 0.34.2 or directly from master even). 

cc @marbar3778 do you agree?

**Comment by marbar3778** [comment]
Sticking to releases makes sense to me. There are some breaking changes even now that I think we can deal with. Reverting to a release will be very cumbersome.
