### ISSUE TITLE
Use rsmt2d lib with passed in NMT instead of repeating the logic in ll-core

### ISSUE THREAD

**Issue by liamsi** [lazyledger/lazyledger-core#172]
Fix this: https://github.com/lazyledger/lazyledger-core/blob/66ff5ac76a07c2dc8f0807068d76293793983312/types/block.go#L220-L222

**Comment by liamsi** [comment]
related: 
- https://github.com/lazyledger/rsmt2d/issues/12#issuecomment-763576720
- https://github.com/lazyledger/lazyledger-core/pull/178#discussion_r588048613

**Comment by evan-forbes** [comment]
:sweat_smile: I actually wrote [some code](https://github.com/evan-forbes/rsmt2d/blob/02d7966e58d9e20d7f49c8b287e46c99451e7abd/extendeddatasquare.go#L44) a while ago to add namespaces after computing the `ExtendedDataSquare`

**Comment by liamsi** [comment]
Is this actively worked on?

**Comment by evan-forbes** [comment]
This is not actively being worked on. It should be a drop in replacement using the new Tree wrapper #238, but it would require some slight reorganizing to avoid an import cycle.

The wrapper itself relies on some constants defined in the types package, and is currently located in the ipld package. If we want to use the tree plugin in the types package we could:

1. move the constants outside of the types package along with moving the wrapper to it's own package
2. move the wrapper to the types package
3. move the wrapper to it's own package and make a reference to the constants in another package.

**Comment by liamsi** [comment]
Cool! Sounds like a low-hanging fruit and that you already have a concrete plan how to tackle it 👍🏼 (I think 3. sounds like the best plan to me but I haven't thought it through really)

**Comment by evan-forbes** [comment]
sounds good! I'll submit a PR later today tentatively using 3 and I think the consequences should be clearer after that.

**Comment by liamsi** [comment]
This can be closed now too, I think?

**Comment by liamsi** [comment]
Confirmed: https://github.com/lazyledger/lazyledger-core/blob/6a4b0a7f21a856f17e72877bab374e9913798eef/types/block.go#L227-L244
