### ISSUE TITLE
Store block Data using IPLD API

### ISSUE THREAD

**Issue by liamsi** [lazyledger/lazyledger-core#185]
## Summary

Store block Data using IPLD API.

## Problem Definition

The proposer needs to store data into its local Merkle dag s.t. it can be sampled or fully downloaded by other peers.

## Proposal

Implement the "read portion" of [adr 002](https://github.com/lazyledger/lazyledger-core/blob/master/docs/lazy-adr/adr-002-ipds-da-sampling.md) and keep the ADR in sync with the actual implementation.

@evan-forbes already started working on this in #178.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by evan-forbes** [comment]
closing because #178 was merged
