### ISSUE TITLE
Catch up with encoding changes

### ISSUE THREAD

**Issue by liamsi** [lazyledger/lazyledger-core#20]
Catch up with https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-055-protobuf-design.md (drops amino and full proto support)
as soon as this lands in master 🎉

**Comment by Liamsi** [comment]
We should probably catch up with the 0.34 release as soon as it's done (independent from if it contains the proto changes or not).

I'll update to latest (upstream) master to make this easier before adding in any more changes here.
