### ISSUE TITLE
DB: pick a single DB

### ISSUE THREAD

**Issue by marbar3778** [lazyledger/lazyledger-core#211]
## Summary

Pick one db and optimize for our needs. 

## Proposal

Remove usage of tm-db and move the DB interface internally to lazyledger core. If we pick badger as our DB we can migrate the current implementation (https://github.com/tendermint/tm-db/tree/master/badgerdb) to our repo. 

After this is done we should try to use the features of a specific DB. 

This work includes removing suport for multiple dbs within e2e tests.

Tendermint is also looking at doing something similar to this. We can collaborate with them and possibly upstream the work. 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by liamsi** [comment]
related:
 - tendermint/tm-db#38
 - tendermint/tendermint#1835 (comment)

**Comment by liamsi** [comment]
> If we pick badger as our DB we can migrate the current implementation (https://github.com/tendermint/tm-db/tree/master/badgerdb) to our repo.

So you are basically suggesting removing the tm-db abstraction, right? We should probably also use the latest badger release then: https://github.com/dgraph-io/badger/releases instead of the [version in tm-db](https://github.com/tendermint/tm-db/blob/53ed3dbaa3eb4c7693ca0aaa2deff093e4675b24/go.mod#L6).

**Comment by tzdybal** [comment]
Why I like badger:
 - actively developed
 - widely used
 - based on recent papers
 - SSD optimized
 - pure go
 - Jepsen tests
 - highly configurable/tunable
 - performance

Personal note: I saw with my own eyes (while working at Dgraph) the emphasis on quality, durability and performance during development.

**Comment by marbar3778** [comment]
> > If we pick badger as our DB we can migrate the current implementation (https://github.com/tendermint/tm-db/tree/master/badgerdb) to our repo.
> 
> So you are basically suggesting removing the tm-db abstraction, right? We should probably also use the latest badger release then: https://github.com/dgraph-io/badger/releases instead of the [version in tm-db](https://github.com/tendermint/tm-db/blob/53ed3dbaa3eb4c7693ca0aaa2deff093e4675b24/go.mod#L6) - I think we can update to github.com/dgraph-io/badger/v3 without any issues.

Yes, remove tm-db abstraction and that repo as a dependency. Absorb the db interface and badger implementation. Seems like the cleanest approach to me. 

Agree with you @tzdybal

**Comment by Wondertan** [comment]
It is important to mention that after implementing a single BadgerV3 DB, we will still end up having two Badger instances in mem. One for LL's data and another for IPFS data, which unluckily uses V2 for now. There is [a plan for an update](https://github.com/ipfs/go-ds-badger/issues/109#issuecomment-767691286), but there were no movements regarding that recently and it is not clear where this will be resolved. Furthermore, even after IPFS updates to the same version, we will still need to figure out the way two use only one instance of Badger, as it's intended to be used. 

@tzdybal, would love to hear the comment from you regarding the use of two Badgers, as you worked closely with it.

**Comment by liamsi** [comment]
Good point! I think It's worth opening an issue (or a [discussion](https://github.com/lazyledger/lazyledger-core/discussions)) for this. Later down the road we ideally would only use one data store for all the things.
