### ISSUE TITLE
merging back potentially split shares into corresponding fields of Block.Data

### ISSUE THREAD

**Issue by liamsi** [lazyledger/lazyledger-core#231]
Currently, there is no method to parse back the block.Data. This will be required to read the block though (#212).

Ideally, this would be implemented in a separate PR. The way this would work is to use the fact, that the shares are encoded with a length delimiter. So by reading the length from a share, we should be able to deduct the number of shares a Tx (messages / interm. state roots/ evidence) actually spans and merge the shares back together (if necessary).

ref: https://github.com/lazyledger/lazyledger-specs/issues/147

**Comment by evan-forbes** [comment]
can we close this issue?

**Comment by liamsi** [comment]
Yes, I think this is completed. Otherwise this would not work: https://github.com/lazyledger/lazyledger-core/blob/7fca45bbd271909c5c14bf1ce60071481540d600/p2p/ipld/read.go#L27
