### ISSUE TITLE
Enforce a minimum square size for empty blocks

### ISSUE THREAD

**Issue by evan-forbes** [lazyledger/lazyledger-core#281]
Currently, empty blocks have empty available data squares, with row and column roots of length == 0. Per the spec, the [AvailableDataHeader](https://github.com/lazyledger/lazyledger-specs/blob/master/specs/data_structures.md#availabledataheader) must have a minimum square size of 1.

We also have to decide what should go in the minimum sized square given an empty block. I think we could use tail padding but am not 100% sure. We might need to reserve the namespace `0,0,0,0,0,0,0,0` and use that for empty blocks.

**Comment by adlerjohn** [comment]
I actually have to fix the specs to have the minimum number of row/column roots to be 2 each. The minimum _original_ data square should be a 1x1, therefore the EDS should be 2x2 minimum.

As for the namespace ID, if there is literally nothing in the block then `TAIL_PADDING_NAMESPACE_ID` should be the namespace ID I think.
