### ISSUE TITLE
Move the IPFS API Object to the `BlockStore`

### ISSUE THREAD

**Issue by evan-forbes** [lazyledger/lazyledger-core#355]
One of the requirements needed to complete #184, is that we have to retrieve block data from IPFS instead of using the `PartSetHeader`. To make this possible, we should move the IPFS API object from the [`consensus.State`](https://github.com/lazyledger/lazyledger-core/blob/7fca45bbd271909c5c14bf1ce60071481540d600/consensus/state.go#L83-L154) object, to the [`store.Blockstore`](https://github.com/lazyledger/lazyledger-core/blob/7fca45bbd271909c5c14bf1ce60071481540d600/store/store.go#L33-L44) object.

**Comment by liamsi** [comment]
Does the BlockStore really need the whole IPFS object? I think the Dag should be enough. 

Also, ideally, the blockstore would only be used for local storage and retrieval. Or, at least the user should be able to indicate if they want to do network IO or only local IO somehow.

**Comment by liamsi** [comment]
Thinking about this further, the blockStore, when accessing the ipfs API in any direction reading/writing, will always potentially do some networking IO. Even when just storing, my understanding is that triggers publishing/gossiping the "have-lists". And that is probably OK. It would still be good if local vs remote would be a bit more explicit (optionally) at least when reading from the store.

**Comment by evan-forbes** [comment]
That's a great point, we definitely need to be explicit when using IPFS to store and retrieve data. This will be very important for future PRs/issues that focus on storing and retrieving data with the IPFS dag object that is being moved in #356
