### ISSUE TITLE
dummyapp: custom block time

### ISSUE THREAD

**Issue by Wondertan** [lazyledger/lazyledger-core#383]
Currently, Dummyapp provides a sleep parameter that freezes block production for the specified period. However, long sleep >10sec causes consensus timeouts leading to endless round restart preventing chain growth, while customizable block time is very helpful in testing block providing and retrievability.

**Comment by marbar3778** [comment]
This can be done by using the values in the config.toml around timeouts for consensus rounds. Unfortunately, these are local configurations instead of network wide. Like most things in tendermint, we have an issue for this....

**Comment by liamsi** [comment]
https://github.com/lazyledger/lazyledger-core/blob/40acb17283ebfe1c49b804a786464b93c2213a97/config/toml.go#L362-L377

**Comment by liamsi** [comment]
@Wondertan I just confirmed that after editing ` ~/.tendermint/config/config.toml` and modfying only the propose timeout to eg.:

```toml
timeout-propose = "12s"
```

```
 ./dummyapp run --dummy.sleep 10s --dummy.txs 10
```
works just fine. Feel free to close the issue if this unblocks you. Otherwise, I think I need more details on how I can help.

**Comment by Wondertan** [comment]
Thanks! This should be enough for my goals
