### ISSUE TITLE
Refactor APIProvider to accomodate manual providing, offline dags, and easy mocks

### ISSUE THREAD

**Issue by evan-forbes** [lazyledger/lazyledger-core#399]
We need a new `APIProvider` that can provide access to the `routing.ContentRouting`, `blockstore.Blockstore`, and `ipld.DAGService` APIs found in the `core.IpfsNode` object. Ideally, this refactor would also be easy to mock only the portions needed so that we can avoid tripping up the CI.

ref #375 and #374

**Comment by Wondertan** [comment]
Synchronously discussed. The decision is to change `APIProvider` to `NodeProvider`:
```go
type NodeProvider func() (*core.IpfsNode, error)
```
