### ISSUE TITLE
Implement tendermint/issue#2639 (preprocessing of blocks)

### ISSUE THREAD

**Issue by liamsi** [lazyledger/lazyledger-core#59]
It would allow us to more cleanly write the intermediate state roots from the (abci) app into the Block.Data. 

Also, clarify if we can also use this mechanism to write the (LL applications') messages into the block data (otherwise we'd have potentially large  blobs in the mem pool for no reason).

ref: https://github.com/tendermint/tendermint/issues/2639 (tendermint issue)
ref: https://github.com/marbar3778/tendermint/pull/17 (a first stab on an implementation by @marbar3778)

**Comment by marbar3778** [comment]
I'm happy to complete my PR and submit it to lazyledger. Will try to do this in the coming days

**Comment by marbar3778** [comment]
I would propose before making this change the `DeliverBlock` change is made. This change will allow me to pass the proof or metadata associated with the preprocessing of the block easily to the application. This is a feature that the tendermint team is looking into but is not a high priority. After talking with @liamsi this could aid in implementing parts of the lazy-ledger spec. 

If there is agreement with this, I can begin to doing needed changes for `deliverblock`

**Comment by liamsi** [comment]
Done in #110.

We probably also want a `FinalizeBlock` step at the end instead of the sequence of BeginBlock, DeliverTx, EndBlock. But this can happen later in tandem with immediate execution (see diagram in #3).

**Comment by marbar3778** [comment]
I have a branch that is 80% done for finalize block. I can complete it in the coming days and open it against ll core
